# -*- coding: utf-8 -*-
"""CIE2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWljsT3EBJ7a4IwRrnod8tLhTloxyA_T
"""

import pandas as pd
import numpy as np
import matplotlib. pyplot as plt
from scipy import stats
df=pd.read_csv('/content/titanic (2) cs.csv')
print(df.info())
print(df.head())
print(df.describe())

df.isnull().sum()

print("Null values before filling:\n", df.isnull().sum())
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Survived'].fillna(df['Survived'].mean(), inplace=True)
print("\nNull values after filling:\n", df.isnull().sum())

count_pclass=df['Pclass'].value_counts()
plt.bar(count_pclass.index,count_pclass.values)
plt.xlabel('Pclass')
plt.ylabel('Count')
plt.title('display the count of pclass')
plt.show()