# -*- coding: utf-8 -*-
"""CIE3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MM6ikNlbInokwo87sHCL7oP9kxBsfKRc
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/content/mtcars.csv')
df

x=df[['mpg']]
x

y=df[['hp']]
y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train

x_test

y_train

y_test

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
lr

y_pred=lr.predict(x_test)
x_pred=lr.predict(x_train)
print("x_pred",x_pred)
print("y_pred",y_pred)

from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

print("mse",mse)
print("mae",mae)
print("r2",r2)
print('rmse',rmse)

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/content/mtcars.csv')
df
x=df[['mpg']]
x
y=df[['hp']]
y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train
x_test
y_train
y_test

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
lr
y_pred=lr.predict(x_test)
x_pred=lr.predict(x_train)
print("x_pred",x_pred)
print("y_pred",y_pred)

from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

print("mse",mse)
print("mae",mae)
print("r2",r2)
print('rmse',rmse)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv('/content/mtcars.csv')
df
x=df[['mpg']]
x
y=df[['hp']]
y
sns.scatterplot(data=df,x=df['mpg'],y=df['hp'])

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['mpg']],df[['hp']],test_size=0.2,random_state=42)
x_train
x_test
y_train
y_test

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
lr
y_pred=lr.predict(x_test)
x_pred=lr.predict(x_train)
print("x_pred",x_pred)
print("y_pred",y_pred)

from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

import numpy as np
rmse=np.sqrt(mse)
rmse

print("mse",mse)
print("mae",mae)
print("r2",r2)
print('rmse',rmse)

plt.scatter (x_train,y_train,color='blue')
plt.plot(x_train,x_pred,color='red')
plt.title('mpg vs hp')
plt.xlabel('mpg')
plt.ylabel('hp')
plt.show()