# -*- coding: utf-8 -*-
"""SEE AIML 24CS404

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydRTOzIhxfIoiE30rE0hgYtpwAohNSti
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("/content/tips.csv")
df.head()
df.info()
df.describe()

print(df.isnull().sum())

df_fill0=df.fillna(0)
print(df_fill0.head())

plt.scatter(df["total_bill"],df["tip"])
plt.xlabel("totalbill")
plt.ylabel("tips")
plt.show()